### ISSUE TITLE
Text under cursorline radically changes color

### ISSUE THREAD

**Issue by r-glebov** [doums/darcula#20] opened 2021-02-15 21:55 UTC
Just wondering if it is a feature or a bug? Is it possible to turn off that kind of color switching?

![screen-rec](https://user-images.githubusercontent.com/8741712/107996369-86cef680-6fe0-11eb-928b-07c9b166eb3a.gif)

**Comment by doums** [comment] 2021-02-16 00:12
Hi, no it's bug.
What do you use, vim, n/vim ? Which version ? Do you use treesitter ?

**Comment by r-glebov** [comment] 2021-02-16 05:29
I'm using neovim 0.5.0, nightly builds, basically any build including the last one had this problem. And I'm using treesitter.

**Comment by doums** [comment] 2021-02-16 08:34
Okay, I didnt tested yet darcula myself on nvim 0.5. It seems they changed something on hi groups compared to nvim 0.4.
I will install 0.5 and fix this.

**Comment by doums** [comment] 2021-03-18 23:08
Hi,

I have played a bit with nvim 0.5 and treesitter. And I had a similar "bug" as you shown but in my case for typescript.
I rapidly identified the cause : it was caused by the plugin `leafgarland/typescript-vim` which also provides syntax and highlight for typescript files, and logically conflict with treesitter.
Just had to remove it from my config and the problem was gone. Plus it is useless now since I use treesitter.

I suspect you are in the same case but for your language, try to disable other plugin that bring syntax and highlight stuff.
I close the issue for now, feel free to open it again if it's not that.

**Closed as completed by doums** 2021-03-18 23:08 UTC
